version: "3.3"

services:
  database:
    container_name: brasileiro_database
    image: postgres
    restart: always
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=brasileirao
      - POSTGRES_USER=brasileirao
    ports:
      - 5434:5432